print(" ⚀")
time.sleep(1.5)
print("        ⚁")
time.sleep(1.5)
print("                ⚂")
time.sleep(1.5)
print("                        ⚃")
time.sleep(1.5)
print("                                 ⚄")
time.sleep(1.5)
print("                                           ⚅")
